### PR TITLE
fix sync_packages

### LINKED ISSUE #81: fix package install/sync script
not sure whether this is really an issue or just outdated on `cob4-paul-stuttgart`:

when logging into the various pcs on `cob4-paul-stuttgart` you see different numbers for updates available, e.g. on base:
```
ssh fxm@cob4-7-b1
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-72-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

34 packages can be updated.
29 updates are security updates.

Last login: Wed Apr 26 08:19:14 2017 from sony-vaio.ipa-apartment.org
***************************
Your robot admin created an overlay for the robot user
```
while on sensorring it is
```
ssh fxm@cob4-7-s1
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-72-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

134 packages can be updated.
34 updates are security updates.

Last login: Wed Apr 26 08:54:08 2017 from cob4-7-b1
***************************
Your robot admin created an overlay for the robot user
```

might be related to #77 
might also be related to the package sync-Script used for the cob-stud-PCs

### PR DESCRIPTION
**Pull request by ipa-fxm**
fix #81 

for some reason https://github.com/ipa320/setup_cob4/commit/414da57e2d3a976f62bc0827daee984595eebcdc introduced changes which broke the sync script, i.e. the packages list was empty for sensorring

this PR now reverts these change and was tested on `cob4-7`

### CODE REVIEW

**Comment by ipa-fxm** [comment]
Someone cheered too soon.

`cob4-7-s1` still was not sync'ed with the other PCs...I ran `sudo ap-get update && sudo apt-get upgrade` manually on `cob4-7-s1`....
this needs to be investigated....something is wrong with `cob4-7-s1` the script provided here works on all other PCs...

**Comment by ipa-fmw** [comment]
script is Ok and can be merged. 

on cob4-7-s1 setup is messed up, so script fails here. `sudo apt-get update` fails (and was always failing) with 
```
W: Failed to fetch https://deb.nodesource.com/node_6.x/dists/trusty/main/source/Sources  Received HTTP code 403 from proxy after CONNECT

W: Failed to fetch https://deb.nodesource.com/node_6.x/dists/trusty/main/binary-amd64/Packages  Received HTTP code 403 from proxy after CONNECT

W: Failed to fetch https://deb.nodesource.com/node_6.x/dists/trusty/main/binary-i386/Packages  Received HTTP code 403 from proxy after CONNECT

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by ipa-fxm** [comment]
@ipa-nhg can you assist us here?
maybe we need to freshly set up `cob4-7-s1`...

File: scripts/sync_packages.sh [hunk 1]
```diff
@@ -1,35 +1,41 @@
 #!/bin/bash
-robot_name="${HOSTNAME//-b1}"
```
Comment (ipa-nhg) [inline scripts/sync_packages.sh]: please use robot_name and not the variable $ROBOT.  I can't ensure that this variable is always right, for example the root user hasn't got a default value. This will be changed as soon as we have a new network configuration, we will use nmap to check which Pcs are connected to the robot intern network.

**Comment by ipa-nhg** [comment]
Solved cob4-7-s1 issue. There was a ` /etc/apt/sources.list.d/nodesource.list`  file where a 32 bits mirror server were defined , I think this was needed to start the SICK 3d sensor for a fair

**Comment by ipa-fxm** [comment]
@ipa-nhg @ipa-fmw 
seems we still have issues with the sync-script...could we investigate this together, please:

While `sync_install.sh` was able to run on all pcs, i.e. not cancel during s1, it did not update/upgrade/sync packages. Atm, there clearly are updates available for upgrading and I installed an additional package `sudo apt-get install maven` on b1 in order to see whether it gets installed on all other pcs....but it doesn't

There are chromium updates available which might be causing the problems...

File: scripts/sync_packages.sh (hunk 1 above)
Comment (ipa-fmw) [inline scripts/sync_packages.sh]: the problem with using `robot_name` from `$HOSTNAME` is that we cannot use the sync script on any other pc except b1, e.g. the torso pcs.
Do you have a suggestion how to handle that without using `ROBOT`? can't we set `ROBOT` by default for the root user with our install scripts?

**Comment by ipa-fmw** [comment]
there was actually no new package installed on the pcs. problem was parsing the list of packages with `xargs` which is not neccessary any more. This is fixed in https://github.com/ipa320/setup_cob4/pull/84/commits/a04f280d88f6f24089c9c60ae91973cd5ed52e6a.

**Comment by ipa-fmw** [comment]
the solution for the problem with the sensoring should not be uncommenting apt-cacher. apt-cacher is used and working on all other pcs too. if we disable apt-cacher it will take forever to download all packages on all cs from online servers.

File: scripts/sync_packages.sh (hunk 1 above)
Comment (ipa-nhg) [inline scripts/sync_packages.sh]: yes, and/or use nmap to find the robot pcs:

`client_list=$(nmap --unprivileged $IP-98 --system-dns | grep report | awk '{print $6}' | sed 's/(//g;s/)//g') `

**Comment by ipa-fxm** [comment]
sync_script was fixed
we only need to test it on another robot, i.e. `cob4-5` (KIST)

the inconsistencies within the apt-sources is tracked in #85

**Comment by ipa-fxm** [comment]
https://github.com/ipa320/cob4/issues/475#issuecomment-300388620

**Comment by ipa-nhg** [comment]
the https://github.com/ipa320/cob4/issues/475#issuecomment-300388620 is not a sync script error, the problem is the setup.. I have 2 options, remove by default the modemmanager package for all the pcs or create a udev rule for the hand to avoid the lock of the modemmanager. 

But if we start now installing ubuntu server, I think ( have to check) that the modemmanager package will not be installed anymore

**Comment by ipa-fxm** [comment]
additionally to fixing cob4-7-h1 pc, we would need to make sure that `modemmanager` does not get installed according to @ipa-nhg's findings https://github.com/ipa320/cob4/issues/475#issuecomment-301812131

**Comment by ipa-fxm** [comment]
@ipa-nhg 
we considered your comment regarding the client list...please review and approve

additional tasks are tracked in #85
