### PR TITLE
Fix upstart install scripts

### LINKED ISSUE #79: fix upstart installation (NHG:2)
after testing #61 today, `cob-start` and other "auto"-scripts did not work anymore

the assumption is that there might have been local, un-tracked changes/adjustments in the copied script files, i.e. **after** they have been copied to `/etc/init.d` using the `install_upstart.sh` script....
such changes should not be required to make the upstart scripts work!
(in case they still are required, at least, they should be made robot-independent and played back into `setup_cob4` as part of the PR)

in general, we should introduce a systematic testing procedure for changes/PRs within upstart scripts:
 - second person (with `sudo` right) checks out the respective feature branch
 - runs the `install_upstart.sh` afresh
 - turn off robot
 - turn on robot
 - then auto-bringup should be up and running

With this procedure, we make sure that not local changes need to be done in the **copied** files, but only in the **original** files from within `setup_cob4` (which is under version control)

@ipa-nhg 
Do you agree to this procedure?

might be related to #52

### PR DESCRIPTION
**Pull request by ipa-nhg**
fix #79 
- both upstart version (only bringup and msh) use the same check_cameras script version (solves symlink error)
- use -f (force) to copy files, allowing the use of the install script also to update  the installed version

### CODE REVIEW

**Comment by ipa-fxm** [comment]
in which order to we have to test/merge these PRs?  #80, #76, #61, #52
@ipa-nhg could you combine them into one and resolve merge conflicts?

**Comment by ipa-nhg** [comment]
This PR can be merged together with #61  already installed and working on cob4-7 and cob4-5

**Comment by ipa-fxm** [comment]
we could finalize this when rolling back to the full CheckCamera procedure on all affected robots....see https://github.com/ipa320/setup_cob4/pull/61#issuecomment-300190565

File: upstart_msh/cob.d/launch/robot/robot.launch [hunk 1]
```diff
@@ -1,13 +1,8 @@
 <?xml version="1.0"?>
 <launch>
 	
-	<param name="/use_sim_time" value="false"/>
-	<arg name="robot" default="cob4-1"/>
-	<!--arg name="pkg_env_config" default="cob_default_env_config"/-->
-
 	<include file="$(find msh_bringup)/launch/all.launch" >
 		<arg name="env-script" value="/u/msh/git/care-o-bot/devel/env.sh"/>
-		<arg name="robot_env" value="saturn-ingolstadt" />
```
Comment (ipa-fxm) [inline upstart_msh/cob.d/launch/robot/robot.launch]: required changes are done in https://github.com/ipa320/msh/pull/758

**Comment by ipa-fxm** [comment]
@ipa-nhg please review our latest changes...and approve

**Comment by ipa-fxm** [comment]
we had the case where it took about 30 mins to pass the check_camera script on cob4-7-t3...
however, afterwards `cob-start` did not start automatically...
but a manual call to `cob-start` passed the ping and `/tmp/check_done` check and started roslaunch...

thus, there seems to be a sync issue in the pre-condition of `cob-start`

File: InstallCob4.sh [hunk 2]
```diff
@@ -66,7 +66,7 @@ function BasicInstallation {
   wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
   echo -e "\n${green}   INFO: Install ROS${NC}\n"
   sudo apt-get update
-  sudo apt-get install ros-indigo-rosbash python-ros-* ros-indigo-care-o-bot-robot -y --force-yes
```
Comment (ipa-nhg) [inline InstallCob4.sh]: are you sure that this can be removed? this was needed to install rosdep (python-rosdep)

File: scripts/cob-shutdown [hunk 3]
```diff
@@ -46,14 +49,18 @@ for client in $client_list; do
...
+    fi
     echo "-------------------------------------------"
     echo "Executing <<waiting for>> on" $client  
     echo "-------------------------------------------"
     echo ""
     shutdown=false
     Crono=0
     while [[ !$shutdown &&  $Crono -le 60 ]]; do
-      ping -c 1 -w 3 $client
+      ping -qc 1 -w 3 $client > /dev/null
```
Comment (ipa-nhg) [inline scripts/cob-shutdown]: what means -q ??

File: upstart_msh/upstart_install.sh [hunk 4]
```diff
@@ -38,16 +55,14 @@ for client in $client_list; do
 	echo "-------------------------------------------"
 	echo ""
 	ssh $client "sudo mkdir -p /etc/ros/$ROS_DISTRO/cob.d"
-	ssh $client "sudo ln -s /u/robot/git/setup_cob4/upstart_msh/cob.d/setup /etc/ros/$ROS_DISTRO/cob.d/setup"
-	ret=${PIPESTATUS[0]}
-	if [ $ret != 0 ] ; then
-		echo "command return an error (error code: $ret), aborting..."
-	fi
+	ssh $client "sudo cp -rf /u/robot/git/setup_cob4/upstart_msh/cob.d /etc/ros/$ROS_DISTRO/"
```
Comment (ipa-nhg) [inline upstart_msh/upstart_install.sh]: this is not required for each client, just on base pc

File: upstart_msh/upstart_install.sh [hunk 5]
```diff
@@ -1,28 +1,45 @@
...
-sudo cp /u/robot/git/setup_cob4/upstart_msh/cob.conf /etc/init/cob.conf
-sudo cp /u/robot/git/setup_cob4/upstart_msh/cob_msh.conf /etc/init/cob_msh.conf
-sudo cp /u/robot/git/setup_cob4/upstart_msh/cob-start /usr/sbin/cob-start
+sudo cp -f /u/robot/git/setup_cob4/upstart_msh/cob-start /usr/sbin/cob-start
 sudo sed -i "s/myrobotname/$robot_name/g" /usr/sbin/cob-start
 sudo sed -i "s/mydistro/$ROS_DISTRO/g" /usr/sbin/cob-start
 sudo sed -i "s/myrobot/$ROBOT/g" /usr/sbin/cob-start
 sudo sed -i "s/myuser/msh/g" /usr/sbin/cob-start
-echo "%users ALL=NOPASSWD:/usr/sbin/cob-start" | sudo tee -a /etc/sudoers
+sudoers_string="%users ALL=NOPASSWD:/usr/sbin/cob-start"
```
Comment (ipa-nhg) [inline upstart_msh/upstart_install.sh]: please be consequence, upstart/install_upstart has other command line for the same function : https://github.com/ipa-nhg/setup_cob4/blob/042f712e572bceaa12ff32ffe9ed93fc31b49367/upstart/upstart_install.sh#L14 , modify both or use here the same command line as upstart_install.sh

**Comment by ipa-fxm** [comment]
I will consider @ipa-nhg's comments and sync upstart with upstart_msh (related #62) asap
